// Package model defines the core data structures used across the application.
package model

// User represents a user entity in the system.
type User struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"-"`
	Role         string `json:"role"`
}

// CreateUserRequest represents the expected payload for creating a new user.
type CreateUserRequest struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// UpdateUserRequest represents the expected payload for updating an existing user.
type UpdateUserRequest struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// LoginRequest represents the expected payload for starting a new session for existing users
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// token resources generated by the server on successful logins
type AuthResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}
